### ISSUE TITLE
Convert eBird API's XML / CSV response to JSON

### ISSUE THREAD

**Issue by jakehockey10** [jakehockey10/bird-compare#1]
We likely need to find a way to convert our responses to JSON.  One quick look at the API's documentation has shown me that at least for some of the endpoints, if not all of them, either return CSV or XML as their response type.

**Comment by Tahani2015** [comment]
This is an easy online converter
http://codebeautify.org/csv-to-xml-json

**Comment by jakehockey10** [comment]
Nice!  This can help us while debugging!  I also found [this](https://code.google.com/p/x2js/).  I'm thinking we'll need to find a solution for us that we can have live up on the server and do the conversion for us, automatically.  We can then use the response to display something right away :)

**Comment by Tahani2015** [comment]
Already supported by eBird API
