### ISSUE TITLE
Implement Leaflet API endpoints we want / need

### ISSUE THREAD

**Issue by jakehockey10** [jakehockey10/bird-compare#10]
We may need all of them, but we should start with the endpoints that are obviously needed.  We can close this when we are ready to move on to another issue.  And if later on, we decide we need another endpoint, we can create a new issue.

**Comment by Tahani2015** [comment]
Now the leaflet map is working :) 
I found the right way to add my access token

**Comment by rshamirza** [comment]
Leaflet API is now working.
